development:
  secret_key_base: d7f375814ff458275167fe9846444e8ccd1a138d1de7d101e57840969b2ab34a5fbda949b33bda05d62bc5e4d49b0d092cf08201bce95b82e83c1a4aa9834ed9
  twilio_phone_number: "5733033256"
  twilio_account_sid: "AC9044cadfcc698694901f7ef1ad74aa61"
  twilio_auth_token: "32f7b9a7d0674fbc519e06f4babc7202"

test:
  secret_key_base: e2d4bb6c70f0a0c0579a412fa8e2b1a54174352e1158cc226b7d7b7fe78351feeac96b91f1ac47b29a7b8e0eb8f1953c26e423f8decf6cc03fc48e7a4764a66c
  twilio_phone_number: "5733033256"
  twilio_account_sid: "AC9044cadfcc698694901f7ef1ad74aa61"
  twilio_auth_token: "32f7b9a7d0674fbc519e06f4babc7202"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
